# Generated by Django 5.0.4 on 2024-05-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_disambiguated',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
